---
description-meta: |
  This book will teach you how to use a variety of tools in R to work with data generated by the National Estuarine Research Reserve's System-Wide Monitoring Program (SWMP). I wrote it for anyone interested in using SWMP data and applying many of the tools and R packages that have been developed (i.e., SWMPr, SWMPrExtension) to make the SWMP workflow easier. This book builds upon the work of several others, but serves as a compilation of ways in which to implement these wonderful tools.
---

## Welcome {.unnumbered}

This is the website for **"Working with SWMP Data Tools"**. This book will teach you how to use a variety of tools in R to work with data generated by the National Estuarine Research Reserve's System-Wide Monitoring Program (SWMP). I wrote it for anyone who has a familiarity with R programming, that may work within the NERRS system, or who uses the NERRS Centralized Data Management Office (CDMO)'s data portal to access and download SWMP data. Many of the packages and workflows presented in this book have been created by others and are cited wherever possible.

::: {.callout-note appearance="simple"}
This book is a current work-in-progress. This material will reflect when a first edition of this work is finalized.
:::


## License

This website is (and will always be) **free to use**, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License. If you'd like a **physical copy** of the book, click the download button in the upper left-hand side to download a pdf version for your own use. If you'd like to give back, please consider reporting a typo or leaving a pull request at [github.com/skdunnigan/swmp-data-edu](https://skdunnigan/swmp-data-edu).